//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErmiiSoft.MkdsKartAiParamEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErmiiSoft.MkdsKartAiParamEditor.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old_yoshi_gc
        ///old_mario_gc
        ///luigi_course
        ///dokan_course
        ///test1_course
        ///donkey_course
        ///wario_course
        ///nokonoko_course
        ///old_baby_gc
        ///old_mario_sfc
        ///old_momo_64
        ///old_koopa_agb
        ///old_peach_agb
        ///old_luigi_gc
        ///old_noko_sfc
        ///old_frappe_64
        ///clock_course
        ///mansion_course
        ///airship_course
        ///cross_course
        ///test_circle
        ///bank_course
        ///old_hyudoro_64
        ///ridge_course
        ///mario_course
        ///garden_course
        ///desert_course
        ///town_course
        ///rainbow_course
        ///snow_course
        ///beach_course
        ///koopa_course
        ///pinball_course
        ///stadium_course
        ///old_donut_sfc
        ///old_c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultCourseList {
            get {
                return ResourceManager.GetString("DefaultCourseList", resourceCulture);
            }
        }
    }
}
